INSERT INTO genres VALUES(1,'Rock');
INSERT INTO genres VALUES(2,'Jazz');
INSERT INTO genres VALUES(3,'Metal');
INSERT INTO genres VALUES(4,'Alternative & Punk');
INSERT INTO genres VALUES(5,'Rock And Roll');
INSERT INTO genres VALUES(6,'Blues');
INSERT INTO genres VALUES(7,'Latin');
INSERT INTO genres VALUES(8,'Reggae');
INSERT INTO genres VALUES(9,'Pop');
INSERT INTO genres VALUES(10,'Soundtrack');
INSERT INTO genres VALUES(11,'Bossa Nova');
INSERT INTO genres VALUES(12,'Easy Listening');
INSERT INTO genres VALUES(13,'Heavy Metal');
INSERT INTO genres VALUES(14,'R&B/Soul');
INSERT INTO genres VALUES(15,'Electronica/Dance');
INSERT INTO genres VALUES(16,'World');
INSERT INTO genres VALUES(17,'Hip Hop/Rap');
INSERT INTO genres VALUES(18,'Science Fiction');
INSERT INTO genres VALUES(19,'TV Shows');
INSERT INTO genres VALUES(20,'Sci Fi & Fantasy');
INSERT INTO genres VALUES(21,'Drama');
INSERT INTO genres VALUES(22,'Comedy');
INSERT INTO genres VALUES(23,'Alternative');
INSERT INTO genres VALUES(24,'Classical');
INSERT INTO genres VALUES(25,'Opera');
meh;