INSERT INTO playlists VALUES(1,'Music');
INSERT INTO playlists VALUES(2,'Movies');
INSERT INTO playlists VALUES(3,'TV Shows');
INSERT INTO playlists VALUES(4,'Audiobooks');
INSERT INTO playlists VALUES(5,'90’s Music');
INSERT INTO playlists VALUES(6,'Audiobooks');
INSERT INTO playlists VALUES(7,'Movies');
INSERT INTO playlists VALUES(8,'Music');
INSERT INTO playlists VALUES(9,'Music Videos');
INSERT INTO playlists VALUES(10,'TV Shows');
INSERT INTO playlists VALUES(11,'Brazilian Music');
INSERT INTO playlists VALUES(12,'Classical');
INSERT INTO playlists VALUES(13,'Classical 101 - Deep Cuts');
INSERT INTO playlists VALUES(14,'Classical 101 - Next Steps');
INSERT INTO playlists VALUES(15,'Classical 101 - The Basics');
INSERT INTO playlists VALUES(16,'Grunge');
INSERT INTO playlists VALUES(17,'Heavy Metal Classic');
INSERT INTO playlists VALUES(18,'On-The-Go 1');