--|sqlflow| connection: admin

-- args 1=user, 2=password

DECLARE cnt NUMBER;
BEGIN
  SELECT count(*) INTO cnt FROM dba_users WHERE UPPER(username)='TEST';
  IF cnt = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER test IDENTIFIED BY test';
    EXECUTE IMMEDIATE 'GRANT CONNECT TO test';
    EXECUTE IMMEDIATE 'GRANT CONNECT,RESOURCE,DBA TO test';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION, GRANT ANY PRIVILEGE TO test';
    EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO test';
    EXECUTE IMMEDIATE 'GRANT CREATE ANY DIRECTORY TO test';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON SYS.UTL_FILE TO test';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON SYS.DBMS_LOCK TO test';
    EXECUTE IMMEDIATE 'GRANT SELECT ON v_$session TO test';
    EXECUTE IMMEDIATE 'GRANT ALTER SYSTEM TO test';
  END IF;
END;
/
